/*人员删除触发器*/
DROP TRIGGER if EXISTS TriDelUser;
CREATE TRIGGER TriDelUser BEFORE DELETE
ON T_User
FOR EACH ROW
BEGIN
	DELETE FROM T_Record WHERE U_Id=OLD.U_Id;
END;

/*座位删除触发器*/
DROP TRIGGER if EXISTS TriDelSeat;
CREATE TRIGGER TriDelSeat BEFORE DELETE
ON T_Seat
FOR EACH ROW
BEGIN
	DELETE FROM T_Record WHERE S_Id=OLD.S_Id;
END;

/*场次删除触发器*/
DROP TRIGGER if EXISTS TriDelOnMovie;
CREATE TRIGGER TriDelOnMovie BEFORE DELETE
ON T_OnMovie
FOR EACH ROW
BEGIN
	DELETE FROM T_Record WHERE O_Id=OLD.O_Id;
	DELETE FROM T_Seat WHERE O_Id=OLD.O_Id;
END;

/*影厅删除触发器*/
DROP TRIGGER if EXISTS TriDelTheater;
CREATE TRIGGER TriDelTheater BEFORE DELETE
ON T_Theater
FOR EACH ROW
BEGIN
	DELETE FROM T_OnMovie WHERE T_Id=OLD.T_Id;
END;

/*影片删除触发器*/
DROP TRIGGER if EXISTS TriDelMovie;
CREATE TRIGGER TriDelMovie BEFORE DELETE
ON T_Movie
FOR EACH ROW
BEGIN
	DELETE FROM T_OnMovie WHERE M_Id=OLD.M_Id;
END;
